CREATE TABLE IF NOT EXISTS users (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY 
	name VARCHAR(50) NOT NULL,
	description TEXT,
	author_id INT(10) UNSIGNED NOT NULL,
	project_id INT(10) UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS project_users (
	project_id INT(10) UNSIGNED NOT NULL,
	user_id INT(10) UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS assigned_users (
	task_id INT(10) UNSIGNED NOT NULL,
	user_id INT(10) UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS files_1 (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	path VARCHAR(255) NOT NULL,
	project_id INT(10) DEFAULT NULL,
	task_id INT(10) DEFAULT NULL
);